ClusterName=nyx-cluster
SlurmctldHost=head
SlurmUser=slurm

StateSaveLocation=/var/lib/slurm/slurmctld
SlurmdSpoolDir=/var/lib/slurm/slurmd
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

AuthType=auth/munge
CryptoType=crypto/munge

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core


ReturnToService=1

NodeName=compute-1 CPUs=4 RealMemory=2000 State=UNKNOWN
NodeName=compute-2 CPUs=4 RealMemory=2000 State=UNKNOWN

PartitionName=normal Nodes=compute-1,compute-2 Default=YES State=UP
PartitionName=gpu Nodes=compute-2 Default=NO State=UP
